[package]
name = "elora-render"
description = "wgpu-2D-Renderer von Elora"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
elora-sim.workspace = true
wgpu.workspace = true
lyon.workspace = true
bytemuck.workspace = true
thiserror.workspace = true

[lints]
workspace = true
