# Elora-Testkarte für CTF und Teammodi (M4)
format = 1
name   = "CTF-Test"
author = "Elora-Team"

[grid]
tiles = '''
################################################################
#..............................................................#
#..............................................................#
#..............................................................#
#..............................ah..............................#
#...........................########...........................#
#..............................................................#
#..............................................................#
#.............%%%%%%%......................%%%%%%%.............#
#..............................................................#
#..............................................................#
#.........................D....L.G...J.........................#
#.......................################.......................#
#..............................................................#
#..r..R.R..............................................B.B..b..#
###########..........................................###########
#..............................................................#
#..............................................................#
#..............................................................#
#...........h...G...W......................W...L...h...........#
##########################^^^^^^^^^^^^##########################
################################################################
'''
