# Elora-Karte
format  = 1                 # Formatversion
name    = "Sandbox"
author  = "Elora-Team"

# Optional: eigene Zeichen oder Überschreibungen der Standard-Legende
# [legend]
# "x" = "death"

[grid]
tiles = '''
################################################
#..............................................#
#..............................................#
#...a.D.................................J.h....#
#..#####..........%%%%%%%%%%..........#####....#
#..............................................#
#..............................................#
#....................X..G......................#
#..................############................#
#..............................................#
#....S..................................S......#
#..######....................................###
#..........%%%%..................%%%%..........#
#..............................................#
#.....................W.L......................#
#....................#######...................#
#..S..........................................S#
#.....h..........................a.............#
#########^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^#########
################################################
'''
