# Elora-Karte
format  = 1                 # Formatversion
name    = "Sandbox"
author  = "Elora-Team"

# Optional: eigene Zeichen oder Überschreibungen der Standard-Legende
# [legend]
# "~" = "death"

[grid]
tiles = '''
################################################
#..............................................#
#..............................................#
#...a.....................................h....#
#..#####..........%%%%%%%%%%..........#####....#
#..............................................#
#..............................................#
#.......................G......................#
#..................############................#
#..............................................#
#....S..................................S......#
#..######....................................###
#..........%%%%..................%%%%..........#
#..............................................#
#.......................L......................#
#....................#######...................#
#..S..........................................S#
#.....h..........................a.............#
#########^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^#########
################################################
'''
